antitle: Bryan Alay Blog
description: Blog personal
author: Bryan Alay
avatar: /utglogo.png
email: Bryanalmi27@hotmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: bryanalay
  card: summary
logo: utglogo.png
social:
  name: Bryan Alay Miranda
  links:
    - https://twitter.com/UtgamerThe
    - https://www.facebook.com/bryanalmi/
    - https://github.com/bryanalay
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es
